language: cpp
compiler:
  - gcc
  - clang
before_install: ./scripts/travis/install-deps.sh
before_script:
  - git submodule init
  - git submodule update
script: cd jsoncpp && scons platform='linux-gcc' && cd .. && scons
notifications:
  recipients:
    - tommy@monetas.net
  email:
    on_success: change
    on_failure: always
