language: cpp
compiler:
  - gcc
  - clang
before_install: ./scripts/travis/install-deps.sh
script: scons
notifications:
  recipients:
    - tommy@monetas.net
  email:
    on_success: change
    on_failure: always
