language: cpp
compiler:
  - gcc
  - clang
before_install: ./scripts/travis/install-deps.sh
install: sudo apt-get install scons
before_script:
  - git submodule init
  - git submodule update
script: cd jsoncpp && scons && cd .. && scons
